/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/**
 * This is a read-only filesystem that uses a sorted hash table to locate
 * entries in a monolithic binary. The binary is generated by the mkfrogfs
 * tool that comes with this source distribution.
 */

#include "log.h"
#include "frogfs/frogfs.h"
#include "frogfs/format.h"

#if defined(ESP_PLATFORM)
# include "esp_partition.h"
# include "spi_flash_mmap.h"
#endif

#include <assert.h>
#include <inttypes.h>
#include <limits.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>


#define IS_FLAT (d->depth != 0xFF)

// Returns the current or next highest multiple of 4.
static inline size_t align(size_t n)
{
    return ((n + 4 - 1) / 4) * 4;
}

// String hashing function.
static inline uint32_t djb2_hash(const char *s)
{
    unsigned long hash = 5381;

    while (*s) {
        /* hash = hash * 33 ^ c */
        hash = ((hash << 5) + hash) ^ *s++;
    }

    return hash;
}

frogfs_fs_t *frogfs_init(frogfs_config_t *conf)
{
    frogfs_fs_t *fs = calloc(1, sizeof(frogfs_fs_t));
    if (fs == NULL) {
        LOGE("calloc failed");
        return NULL;
    }

    LOGV("%p", fs);

    fs->head = (const void *) conf->addr;
    if (fs->head == NULL) {
#if defined (ESP_PLATFORM)
        esp_partition_subtype_t subtype = conf->part_label ?
                ESP_PARTITION_SUBTYPE_ANY :
                ESP_PARTITION_SUBTYPE_DATA_ESPHTTPD;
        const esp_partition_t* partition = esp_partition_find_first(
                ESP_PARTITION_TYPE_DATA, subtype, conf->part_label);

        if (partition == NULL) {
            LOGE("unable to find frogfs partition");
            goto err_out;
        }

        if (esp_partition_mmap(partition, 0, partition->size,
                SPI_FLASH_MMAP_DATA, (const void **)&fs->head,
                &fs->mmap_handle) != ESP_OK) {
            LOGE("mmap failed");
            goto err_out;
        }
#else
        LOGE("flash mmap not enabled and addr is NULL");
        goto err_out;
#endif
    }

    if (fs->head->magic != FROGFS_MAGIC) {
        LOGE("frogfs magic not found");
        goto err_out;
    }

    if (fs->head->ver_major != FROGFS_VER_MAJOR) {
        LOGE("frogfs major version mismatch. filesystem is v%d.%d and this "
                "library is v%d.%d", fs->head->ver_major, fs->head->ver_minor,
                FROGFS_VER_MAJOR, FROGFS_VER_MINOR);
        goto err_out;
    }

    fs->num_entries = fs->head->num_entries;
    fs->hash = (const void *) fs->head + sizeof(frogfs_head_t);
    fs->root = (const void *) fs->hash + (sizeof(frogfs_hash_t) * fs->num_entries);

    return fs;

err_out:
    frogfs_deinit(fs);
    return NULL;
}

void frogfs_deinit(frogfs_fs_t *fs)
{
    LOGV("%p", fs);

#if defined(ESP_PLATFORM)
    if (fs->mmap_handle) {
        spi_flash_munmap(fs->mmap_handle);
    }
#endif
    free(fs);
}

const frogfs_entry_t *frogfs_get_entry(const frogfs_fs_t *fs, const char *path)
{
    assert(fs != NULL);
    assert(path != NULL);

    while (*path == '/') {
        path++;
    }
    LOGV("'%s'", path);

    uint32_t hash = djb2_hash(path);
    LOGV("hash %08"PRIx32, hash);

    int first = 0;
    int last = fs->num_entries - 1;
    int middle;
    const frogfs_hash_t *e;

    while (first <= last) {
        middle = first + (last - first) / 2;
        e = &fs->hash[middle];
        if (e->hash == hash) {
            break;
        } else if (e->hash < hash) {
            first = middle + 1;
        } else {
            last = middle - 1;
        }
    }

    if (first > last) {
        LOGV("no match");
        return NULL;
    }

    /* move e to the first match */
    while (middle > 0) {
        e = fs->hash + middle;
        if ((e - 1)->hash != hash) {
            break;
        }
        middle--;
    }

    /* walk through canidates and look for a match */
    const frogfs_entry_t *entry;
    do {
        entry = (const void *) fs->head + e->offs;
        char *match = frogfs_get_path(fs, entry);
        if (strcmp(path, match) == 0) {
            free(match);
            LOGV("entry %d", middle);
            return entry;
        }
        free(match);
        entry++;
        middle++;
    } while ((middle < last) && (e->hash == hash));

    LOGW("unable to find entry");
    return NULL;
}

const char *frogfs_get_name(const frogfs_entry_t *entry)
{
    if (FROGFS_ISDIR(entry)) {
        return (const void *) entry + 8 + (entry->child_count * 4);
    } else if (FROGFS_ISFILE(entry) && !FROGFS_ISCOMP(entry)) {
        return (const void *) entry + 16;
    } else {
        return (const void *) entry + 20;
    }
}

char *frogfs_get_path(const frogfs_fs_t *fs, const frogfs_entry_t *entry)
{
    assert(entry != NULL);

    char *path = calloc(PATH_MAX, 1);
    size_t len = 0;
    if (!path) {
        return NULL;
    }

    if (entry->parent == 0) {
        return path;
    }

    while (entry->parent != 0 && len + entry->seg_sz + 1 < PATH_MAX - 1) {
        const frogfs_entry_t *parent = (const void *) fs->head + entry->parent;
        if ((const void *) parent == (const void *) fs->root) {
            memmove(path + entry->seg_sz, path, len);
            memcpy(path, frogfs_get_name(entry), entry->seg_sz);
            len += entry->seg_sz;
            break;
        } else {
            memmove(path + entry->seg_sz + 1, path, len + 1);
            path[0] = '/';
            memcpy(path + 1, frogfs_get_name(entry), entry->seg_sz);
            len += entry->seg_sz + 1;
        }
        entry = parent;
    }

    return path;
}

void frogfs_stat(const frogfs_fs_t *fs, const frogfs_entry_t *entry,
        frogfs_stat_t *st)
{
    assert(fs != NULL);
    assert(entry != NULL);

    memset(st, 0, sizeof(*st));
    if (FROGFS_ISDIR(entry)) {
        st->type = FROGFS_ENTRY_TYPE_DIR;
    } else {
        st->type = FROGFS_ENTRY_TYPE_FILE;
        const frogfs_file_t *file = (const void *) entry;
        st->compression = entry->compression;
        if (st->compression) {
            const frogfs_comp_t *comp = (const void *) entry;
            st->data_sz = comp->data_sz;
            st->real_sz = comp->real_sz;
        } else {
            st->data_sz = file->data_sz;
            st->real_sz = file->data_sz;
        }
    }
}

frogfs_f_t *frogfs_open(const frogfs_fs_t *fs, const frogfs_entry_t *entry,
        unsigned int flags)
{
    assert(fs != NULL);
    assert(entry != NULL);

    if (FROGFS_ISDIR(entry)) {
        return NULL;
    }

    const frogfs_file_t *file = (const void *) entry;

    frogfs_f_t *f = calloc(1, sizeof(frogfs_f_t));
    if (f == NULL) {
        LOGE("calloc failed");
        goto err_out;
    }

    LOGV("%p", f);

    f->fs = fs;
    f->file = file;
    f->data_start = (const void *) fs->head + file->data_offs;
    f->data_ptr = f->data_start;
    f->data_sz = file->data_sz;
    f->flags = flags;

    if (entry->compression == 0 || flags & FROGFS_OPEN_RAW) {
        f->real_sz = file->data_sz;
        f->decomp_funcs = &frogfs_decomp_raw;
    }
#if defined(CONFIG_FROGFS_USE_DEFLATE)
    else if (entry->compression == FROGFS_COMP_ALGO_DEFLATE) {
        f->real_sz = ((frogfs_comp_t *) file)->real_sz;
        f->decomp_funcs = &frogfs_decomp_deflate;
    }
#endif
#if defined(CONFIG_FROGFS_USE_HEATSHRINK)
    else if (entry->compression == FROGFS_COMP_ALGO_HEATSHRINK) {
        f->real_sz = ((frogfs_comp_t *) file)->real_sz;
        f->decomp_funcs = &frogfs_decomp_heatshrink;
    }
#endif
    else {
        LOGE("unknown compression type %d", entry->compression)
        goto err_out;
    }

    if (f->decomp_funcs->open) {
        if (f->decomp_funcs->open(f, flags) < 0) {
            LOGE("decomp_funcs->fopen");
            goto err_out;
        }
    }

    return f;

err_out:
    frogfs_close(f);
    return NULL;
}

void frogfs_close(frogfs_f_t *f)
{
    if (f == NULL) {
        /* do nothing */
        return;
    }

    if (f->decomp_funcs && f->decomp_funcs->close) {
        f->decomp_funcs->close(f);
    }

    LOGV("%p", f);

    free(f);
}

ssize_t frogfs_read(frogfs_f_t *f, void *buf, size_t len)
{
    assert(f != NULL);

    if (f->decomp_funcs->read) {
        return f->decomp_funcs->read(f, buf, len);
    }

    return -1;
}

ssize_t frogfs_seek(frogfs_f_t *f, long offset, int mode)
{
    assert(f != NULL);

    if (f->decomp_funcs->seek) {
        return f->decomp_funcs->seek(f, offset, mode);
    }

    return -1;
}

size_t frogfs_tell(frogfs_f_t *f)
{
    assert(f != NULL);

    if (f->decomp_funcs->tell) {
        return f->decomp_funcs->tell(f);
    }

    return -1;
}

size_t frogfs_access(frogfs_f_t *f, const void **buf)
{
    assert(f != NULL);

    *buf = f->data_start;
    return f->data_sz;
}

frogfs_d_t *frogfs_opendir(frogfs_fs_t *fs, const frogfs_entry_t *entry)
{
    assert(fs != NULL);

    if (entry != NULL && FROGFS_ISFILE(entry)) {
        return NULL;
    }

    frogfs_d_t *d = calloc(1, sizeof(frogfs_d_t));
    if (d == NULL) {
        LOGE("calloc failed");
        return NULL;
    }

    d->fs = fs;
    if (entry == NULL) {
        d->dir = fs->root;
    } else {
        d->dir = (const void *) entry;
        d->depth = 0xFF;
    }

    return d;
}

void frogfs_closedir(frogfs_d_t *d)
{
    if (d == NULL) {
        return;
    }

    free(d);
}

const frogfs_entry_t *frogfs_readdir(frogfs_d_t *d)
{
    const frogfs_entry_t *entry = NULL;

    if (d->dir == NULL) {
        return NULL;
    }

    if (IS_FLAT) {
        if (d->index == 0) {
            d->depth = 0;
            d->dir = d->fs->root;
            d->pos[0] = 0;
        }
again:
        if (d->pos[d->depth] < d->dir->entry.child_count) {
            entry = (const void *) d->fs->head +
                    d->dir->children[d->pos[d->depth]++];
            if (entry->child_count < 0xFF00) {
                d->dir = (const void *) entry;
                d->pos[++d->depth] = 0;
            }
        } else if (d->depth == 0) {
            entry = NULL;
        } else {
            d->dir = (const void *) d->fs->head + d->dir->entry.parent;
            d->depth--;
            goto again;
        }
    } else if (d->pos[0] != d->dir->entry.child_count) {
        entry = (const void *) d->fs->head + d->dir->children[d->pos[0]++];
    }

    d->index++;
    return entry;
}

void frogfs_rewinddir(frogfs_d_t *d)
{
    assert(d != NULL);

    d->index = 0;
}

void frogfs_seekdir(frogfs_d_t *d, uint16_t loc)
{
    assert(d != NULL);

    frogfs_rewinddir(d);
    while (d->index < loc) {
        frogfs_readdir(d);
    }
}

uint16_t frogfs_telldir(frogfs_d_t *d)
{
    assert(d != NULL);

    return d->index;
}
